# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventCalendar.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventCalendar(object):
    def setupUi(self, ventCalendar):
        ventCalendar.setObjectName("ventCalendar")
        ventCalendar.resize(365, 254)
        self.Calendar = QtWidgets.QCalendarWidget(ventCalendar)
        self.Calendar.setGeometry(QtCore.QRect(0, 0, 361, 251))
        self.Calendar.setObjectName("Calendar")

        self.retranslateUi(ventCalendar)
        QtCore.QMetaObject.connectSlotsByName(ventCalendar)

    def retranslateUi(self, ventCalendar):
        _translate = QtCore.QCoreApplication.translate
        ventCalendar.setWindowTitle(_translate("ventCalendar", "Fecha Alta"))
