# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventSalir.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventSalir(object):
    def setupUi(self, ventSalir):
        ventSalir.setObjectName("ventSalir")
        ventSalir.resize(415, 167)
        ventSalir.setModal(True)
        self.btnBoxSalir = QtWidgets.QDialogButtonBox(ventSalir)
        self.btnBoxSalir.setGeometry(QtCore.QRect(130, 110, 161, 32))
        self.btnBoxSalir.setOrientation(QtCore.Qt.Horizontal)
        self.btnBoxSalir.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.btnBoxSalir.setObjectName("btnBoxSalir")
        self.lblMenSAlir = QtWidgets.QLabel(ventSalir)
        self.lblMenSAlir.setGeometry(QtCore.QRect(100, 40, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblMenSAlir.setFont(font)
        self.lblMenSAlir.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblMenSAlir.setObjectName("lblMenSAlir")
        self.lblImgSalir = QtWidgets.QLabel(ventSalir)
        self.lblImgSalir.setGeometry(QtCore.QRect(-10, 30, 111, 51))
        self.lblImgSalir.setText("")
        self.lblImgSalir.setPixmap(QtGui.QPixmap(":/avisoSalir/iconoAviso.png"))
        self.lblImgSalir.setScaledContents(True)
        self.lblImgSalir.setAlignment(QtCore.Qt.AlignCenter)
        self.lblImgSalir.setObjectName("lblImgSalir")

        self.retranslateUi(ventSalir)
        self.btnBoxSalir.accepted.connect(ventSalir.accept)
        self.btnBoxSalir.rejected.connect(ventSalir.reject)
        QtCore.QMetaObject.connectSlotsByName(ventSalir)

    def retranslateUi(self, ventSalir):
        _translate = QtCore.QCoreApplication.translate
        ventSalir.setWindowTitle(_translate("ventSalir", "Salir"))
        self.lblMenSAlir.setText(_translate("ventSalir", "¿Está seguro que desea salir de la aplicación?"))
import avisoSalir_rc
