# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventabout.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgAbout(object):
    def setupUi(self, dlgAbout):
        dlgAbout.setObjectName("dlgAbout")
        dlgAbout.setWindowModality(QtCore.Qt.WindowModal)
        dlgAbout.resize(370, 232)
        self.lblVersion = QtWidgets.QLabel(dlgAbout)
        self.lblVersion.setGeometry(QtCore.QRect(100, 100, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblVersion.setFont(font)
        self.lblVersion.setObjectName("lblVersion")
        self.lblLogo = QtWidgets.QLabel(dlgAbout)
        self.lblLogo.setGeometry(QtCore.QRect(150, 20, 71, 61))
        self.lblLogo.setText("")
        self.lblLogo.setPixmap(QtGui.QPixmap("../BESADAPEREZ/img/logo.jpg"))
        self.lblLogo.setScaledContents(True)
        self.lblLogo.setObjectName("lblLogo")
        self.lblNombre = QtWidgets.QLabel(dlgAbout)
        self.lblNombre.setGeometry(QtCore.QRect(120, 130, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblNombre.setFont(font)
        self.lblNombre.setObjectName("lblNombre")
        self.btnCerrar = QtWidgets.QPushButton(dlgAbout)
        self.btnCerrar.setGeometry(QtCore.QRect(150, 180, 75, 23))
        self.btnCerrar.setObjectName("btnCerrar")

        self.retranslateUi(dlgAbout)
        QtCore.QMetaObject.connectSlotsByName(dlgAbout)

    def retranslateUi(self, dlgAbout):
        _translate = QtCore.QCoreApplication.translate
        dlgAbout.setWindowTitle(_translate("dlgAbout", "Dialog"))
        self.lblVersion.setText(_translate("dlgAbout", "Versión del programa: 0.0.1"))
        self.lblNombre.setText(_translate("dlgAbout", "Oscar Blanco Lorenzo"))
        self.btnCerrar.setText(_translate("dlgAbout", "Cerrar"))
